const stateCodes = {
  abia: 'AB',
  abuja: 'FC',
  adamawa: 'AD',
  'akwa ibom': 'AK',
  anambra: 'AN',
  bauchi: 'BA',
  bayelsa: 'BY',
  benue: 'BE',
  borno: 'BO',
  'cross river': 'CR',
  delta: 'DE',
  ebonyi: 'EB',
  edo: 'ED',
  ekiti: 'EK',
  enugu: 'EN',
  gombe: 'GO',
  imo: 'IM',
  jigawa: 'JI',
  kaduna: 'KD',
  kano: 'KN',
  katsina: 'KT',
  kebbi: 'KE',
  kogi: 'KO',
  kwara: 'KW',
  lagos: 'LA',
  nasarawa: 'NA',
  niger: 'NI',
  ogun: 'OG',
  ondo: 'ON',
  osun: 'OS',
  oyo: 'OY',
  plateau: 'PL',
  rivers: 'RI',
  sokoto: 'SO',
  taraba: 'TA',
  yobe: 'YO',
  zamfara: 'ZA'
};

export default stateCodes;
